-- GENERATED by scripts/generate-seed-sql.ts from lib/config.ts. Do not edit by hand.
-- Idempotent: never overwrites rows the owner has since edited.
begin;

insert into public.plan_tiers (id, name, duration_days, tagline, is_popular, is_active, sort_order) values
('trial', '3 Day Trial', 3, 'Perfect for trying our meals', false, true, 10),
('weekly', 'Weekly Plan', 6, 'Most popular choice', true, true, 20),
('monthly', 'Monthly Plan', 24, 'Best value', false, true, 30),
('salad', 'Salad Plan', 6, 'Fresh & healthy', false, true, 40)
on conflict (id) do nothing;

insert into public.plan_options (id, tier_id, food_type, meal_count, total_price, is_active, sort_order) values
('trial-veg-1', 'trial', 'Veg', 1, 750, true, 10),
('trial-veg-2', 'trial', 'Veg', 2, 1440, true, 20),
('trial-nonveg-1', 'trial', 'Non-Veg', 1, 825, true, 30),
('trial-nonveg-2', 'trial', 'Non-Veg', 2, 1500, true, 40),
('weekly-veg-1', 'weekly', 'Veg', 1, 1350, true, 50),
('weekly-veg-2', 'weekly', 'Veg', 2, 2520, true, 60),
('weekly-nonveg-1', 'weekly', 'Non-Veg', 1, 1440, true, 70),
('weekly-nonveg-2', 'weekly', 'Non-Veg', 2, 2700, true, 80),
('monthly-veg-1', 'monthly', 'Veg', 1, 4560, true, 90),
('monthly-veg-2', 'monthly', 'Veg', 2, 9120, true, 100),
('monthly-nonveg-1', 'monthly', 'Non-Veg', 1, 5040, true, 110),
('monthly-nonveg-2', 'monthly', 'Non-Veg', 2, 9600, true, 120),
('salad-veg-1', 'salad', 'Veg', 1, 1350, true, 130),
('salad-veg-2', 'salad', 'Veg', 2, 2520, true, 140),
('salad-nonveg-1', 'salad', 'Non-Veg', 1, 1440, true, 150),
('salad-nonveg-2', 'salad', 'Non-Veg', 2, 2700, true, 160)
on conflict (id) do nothing;

insert into public.menu_items (id, category, name, price, is_vegetarian, is_active, sort_order) values
('veg-alfredo-penne-pasta-veg', 'veg', 'Alfredo Penne Pasta Veg', 300, true, true, 10),
('veg-cilantro-penne-pasta-veg', 'veg', 'Cilantro Penne Pasta Veg', 300, true, true, 20),
('veg-basil-penne-pasta-veg', 'veg', 'Basil Penne Pasta Veg', 300, true, true, 30),
('veg-chilli-paneer-with-rice-combo', 'veg', 'Chilli Paneer with Rice Combo', 300, true, true, 40),
('veg-chilli-paneer-with-noodles-combo', 'veg', 'Chilli Paneer with Noodles Combo', 300, true, true, 50),
('veg-chilli-mushroom-with-rice-combo', 'veg', 'Chilli Mushroom with Rice Combo', 280, true, true, 60),
('veg-chilli-mushroom-with-noodles-combo', 'veg', 'Chilli Mushroom with Noodles Combo', 280, true, true, 70),
('veg-grilled-paneer-salad', 'veg', 'Grilled Paneer Salad', 275, true, true, 80),
('veg-caesar-salad-veg', 'veg', 'Caesar Salad Veg', 275, true, true, 90),
('veg-asian-salad-veg', 'veg', 'Asian Salad Veg', 275, true, true, 100),
('veg-tropical-salad-veg', 'veg', 'Tropical Salad Veg', 275, true, true, 110),
('veg-bbq-salad-veg', 'veg', 'BBQ Salad Veg', 275, true, true, 120),
('veg-paneer-tikka-with-ghee-rice', 'veg', 'Paneer Tikka with Ghee Rice', 300, true, true, 130),
('veg-thai-green-curry-with-rice-veg', 'veg', 'Thai Green Curry with Rice Veg', 300, true, true, 140),
('veg-paneer-butter-masala-with-roti', 'veg', 'Paneer Butter Masala with Roti', 300, true, true, 150),
('veg-veg-biriyani', 'veg', 'Veg Biriyani', 250, true, true, 160),
('veg-stroganoff-paneer-with-rice', 'veg', 'Stroganoff Paneer with Rice', 300, true, true, 170),
('veg-veg-kurma-with-roti', 'veg', 'Veg Kurma with Roti', 275, true, true, 180),
('non-veg-alfredo-penne-pasta-chicken', 'non_veg', 'Alfredo Penne Pasta Chicken', 325, false, true, 10),
('non-veg-cilantro-penne-pasta-chicken', 'non_veg', 'Cilantro Penne Pasta Chicken', 325, false, true, 20),
('non-veg-basil-penne-pasta-chicken', 'non_veg', 'Basil Penne Pasta Chicken', 325, false, true, 30),
('non-veg-chilli-chicken-with-rice-combo', 'non_veg', 'Chilli Chicken with Rice Combo', 325, false, true, 40),
('non-veg-chilli-chicken-with-noodles-combo', 'non_veg', 'Chilli Chicken with Noodles Combo', 325, false, true, 50),
('non-veg-asian-salad-chicken', 'non_veg', 'Asian Salad Chicken', 300, false, true, 60),
('non-veg-tropical-chicken-salad', 'non_veg', 'Tropical Chicken Salad', 280, false, true, 70),
('non-veg-grilled-chicken-salad', 'non_veg', 'Grilled Chicken Salad', 300, false, true, 80),
('non-veg-caesar-salad-chicken', 'non_veg', 'Caesar Salad Chicken', 300, false, true, 90),
('non-veg-bbq-chicken-salad', 'non_veg', 'BBQ Chicken Salad', 300, false, true, 100),
('non-veg-tandoori-chicken-salad', 'non_veg', 'Tandoori Chicken Salad', 325, false, true, 110),
('non-veg-chicken-kebab-with-ghee-rice', 'non_veg', 'Chicken Kebab with Ghee Rice', 325, false, true, 120),
('non-veg-butter-chicken-with-roti', 'non_veg', 'Butter Chicken with Roti', 325, false, true, 130),
('non-veg-stroganoff-chicken-with-rice', 'non_veg', 'Stroganoff Chicken with Rice', 325, false, true, 140),
('non-veg-thai-green-curry-chicken-with-rice', 'non_veg', 'Thai Green Curry Chicken with Rice', 325, false, true, 150),
('non-veg-chicken-kurma-with-roti', 'non_veg', 'Chicken Kurma with Roti', 325, false, true, 160),
('non-veg-chicken-65-with-rice', 'non_veg', 'Chicken 65 with Rice', 325, false, true, 170),
('non-veg-chicken-biriyani', 'non_veg', 'Chicken Biriyani', 300, false, true, 180),
('dessert-san-sebastian-cheese-cake', 'dessert', 'San Sebastian Cheese Cake', 350, false, true, 10),
('dessert-tiramisu', 'dessert', 'Tiramisu', 300, false, true, 20),
('dessert-brownie-with-chocolate-sauce-nuts', 'dessert', 'Brownie with Chocolate Sauce & Nuts', 250, false, true, 30),
('dessert-tropical-gudbad', 'dessert', 'Tropical Gudbad', 300, true, true, 40),
('dessert-arabian-gudbad', 'dessert', 'Arabian Gudbad', 300, true, true, 50),
('dessert-death-by-chocolate', 'dessert', 'Death By Chocolate', 300, true, true, 60)
on conflict (id) do nothing;

insert into public.bulk_items (id, category, name, unit, price, is_seasonal, is_active, sort_order) values
('party-veg-paneer-chilly', 'veg', 'Paneer Chilly', 'kg', 1000, false, true, 10),
('party-veg-paneer-ghee-roast', 'veg', 'Paneer Ghee Roast', 'kg', 1250, false, true, 20),
('party-veg-paneer-tikka-masala', 'veg', 'Paneer Tikka Masala', 'kg', 1000, false, true, 30),
('party-veg-paneer-curry-patta', 'veg', 'Paneer Curry Patta', 'kg', 1250, false, true, 40),
('party-veg-palak-paneer', 'veg', 'Palak Paneer', 'kg', 1250, false, true, 50),
('party-veg-gobi-chilly', 'veg', 'Gobi Chilly', 'kg', 800, false, true, 60),
('party-veg-chana-masala', 'veg', 'Chana Masala', 'kg', 800, false, true, 70),
('party-veg-mixed-vegetable-curry', 'veg', 'Mixed Vegetable Curry', 'kg', 800, false, true, 80),
('party-veg-navarathna-kurma', 'veg', 'Navarathna Kurma', 'kg', 1000, false, true, 90),
('party-veg-veg-kurma', 'veg', 'Veg Kurma', 'kg', 800, false, true, 100),
('party-veg-veg-fried-rice', 'veg', 'Veg Fried Rice', 'kg', 800, false, true, 110),
('party-veg-veg-pulav', 'veg', 'Veg Pulav', 'kg', 800, false, true, 120),
('party-veg-veg-biriyani', 'veg', 'Veg Biriyani', 'kg', 1000, false, true, 130),
('party-veg-mushroom-chilly', 'veg', 'Mushroom Chilly', 'kg', 800, false, true, 140),
('party-veg-hot-garlic-mushroom', 'veg', 'Hot Garlic Mushroom', 'kg', 900, false, true, 150),
('party-veg-schezwan-mushroom', 'veg', 'Schezwan Mushroom', 'kg', 900, false, true, 160),
('party-veg-kadle-sukka', 'veg', 'Kadle Sukka', 'kg', 700, false, true, 170),
('party-veg-ghee-rice', 'veg', 'Ghee Rice', 'kg', 700, false, true, 180),
('party-nonveg-chicken-chilly', 'non_veg', 'Chicken Chilly', 'kg', 1250, false, true, 10),
('party-nonveg-chicken-sukka', 'non_veg', 'Chicken Sukka', 'kg', 1250, false, true, 20),
('party-nonveg-pepper-chicken', 'non_veg', 'Pepper Chicken', 'kg', 1250, false, true, 30),
('party-nonveg-chicken-ghee-roast', 'non_veg', 'Chicken Ghee Roast', 'kg', 1500, false, true, 40),
('party-nonveg-chicken-green-masala-curry', 'non_veg', 'Chicken Green Masala Curry', 'kg', 1250, false, true, 50),
('party-nonveg-kundapura-chicken-curry', 'non_veg', 'Kundapura Chicken Curry', 'kg', 1250, false, true, 60),
('party-nonveg-hyderabadi-chicken', 'non_veg', 'Hyderabadi Chicken', 'kg', 1250, false, true, 70),
('party-nonveg-pudina-chicken', 'non_veg', 'Pudina Chicken', 'kg', 1250, false, true, 80),
('party-nonveg-chicken-tikka-masala', 'non_veg', 'Chicken Tikka Masala', 'kg', 1250, false, true, 90),
('party-nonveg-chicken-kebab', 'non_veg', 'Chicken Kebab', 'kg', 1250, false, true, 100),
('party-nonveg-chicken-65', 'non_veg', 'Chicken 65', 'kg', 1250, false, true, 110),
('party-nonveg-chicken-fried-rice', 'non_veg', 'Chicken Fried Rice', 'kg', 1000, false, true, 120),
('party-nonveg-chicken-biriyani', 'non_veg', 'Chicken Biriyani', 'kg', 1250, false, true, 130),
('party-nonveg-mutton-green-masala-curry', 'non_veg', 'Mutton Green Masala Curry', 'kg', 2000, false, true, 140),
('party-nonveg-mutton-pepper-fry', 'non_veg', 'Mutton Pepper Fry', 'kg', 2000, false, true, 150),
('party-nonveg-mutton-sukka', 'non_veg', 'Mutton Sukka', 'kg', 2000, false, true, 160),
('party-nonveg-mutton-rogan-gosh', 'non_veg', 'Mutton Rogan Gosh', 'kg', 2000, false, true, 170),
('party-nonveg-mutton-biriyani', 'non_veg', 'Mutton Biriyani', 'kg', 2500, false, true, 180),
('party-nonveg-prawns-biriyani', 'non_veg', 'Prawns Biriyani', 'kg', 2500, false, true, 190),
('party-nonveg-prawns-curry', 'non_veg', 'Prawns Curry', 'kg', 2000, false, true, 200),
('party-nonveg-fish-curry', 'non_veg', 'Fish Curry', 'kg', null, true, true, 210)
on conflict (id) do nothing;

insert into public.site_settings (key, value) values
('party_minimum_order_label', 'Minimum order quantity: 1kg'),
('party_advance_notice_label', 'Order needs to be placed 24-48 hours in advance depending on the order size.')
on conflict (key) do nothing;

commit;
